### ISSUE TITLE
Wrong  default password for admin

### ISSUE THREAD

**Issue by xros** [openshift/drupal-quickstart#26]
According to the openshift drupal document (https://hub.openshift.com/quickstarts/2-drupal-7),
it says default username/password is admin/openshift_changeme . But wrong password if you create an app using the application panel.

What's the correct password then? Thanks

**Comment by wjiangjay** [comment]
After you create a drupal quickstart app, there should be some message display for you like the following:
![snapshot8](https://cloud.githubusercontent.com/assets/4132382/7929208/e961dca6-092d-11e5-859a-ea87cbf964ea.png)

So the user/password is list here, not the admin/openshift_changeme

**Comment by xros** [comment]
Thank you. I figured it out. Technically it's better for people to download the latest Drupal from its official site due to some latency and buggy stuff. 

But openshift had just done so many great things.

**Comment by bparees** [comment]
thanks @wjiangjay.  @xros can we close this?

**Comment by xros** [comment]
Yeah we can.

2015-06-02 22:04 GMT+08:00 Ben Parees <notifications@github.com>:
